[theme]
base = "light"

primaryColor = "#477062"
backgroundColor = "#F7F7F4"
secondaryBackgroundColor = "#ECE8E1"
textColor = "#1F2937"
borderColor = "#D1C7BA"

font = "sans serif"
headingFont = "sans serif"

baseRadius = "medium"
buttonRadius = "medium"